import { getReading } from './story.js';
// Translation keys are shared by static markup and the interactive lesson UI.
const messages = {
 title:['Word Odyssey 字旅｜你的英文英雄之旅','Word Odyssey | Your English Hero’s Journey'],
 description:['跟著英倫潑墨地圖，走過一百關英雄旅程。先複習、再學習，把每個英文單字變成你的冒險裝備。','Explore 100 chapters across Britain. Review, learn and grow your vocabulary from 1,200 to 7,000 words.'],
 skip:['跳到主要內容','Skip to main content'], home:['字旅首頁','Word Odyssey home'], tagline:['字 旅 · 英 文 英 雄 之 旅','YOUR ENGLISH HERO’S JOURNEY'], navigation:['主要導覽','Main navigation'],
 journey:['冒險地圖','Adventure map'],words:['我的單字行囊','My word collection'],journal:['成長手札','Journey journal'],
 note:['每一個單字，都是走向世界的一小步。','Every word is a small step into a wider world.'],local:['進度儲存在此瀏覽器','Progress saved in this browser'],temporary:['暫存模式，請匯出備份','Temporary mode — export a backup'],pace:['慢慢學，也能走很遠','Small steps take you far'],
 heroArt:['彩色潑墨英倫風景：旅人沿鄉間小徑，越過石橋、尖塔城鎮，走向遠方城堡。','A colourful watercolour landscape: a traveller follows a country path past a stone bridge and spired towns towards a distant castle.'],
 heroSub:['從一個單字開始，走出你的英雄之旅。','Begin with one word. Become the hero of your own journey.'],heroDescription:['重溫走過的路，帶上新的力量。下一段冒險，從今天的你出發。','Revisit familiar paths. Gather new strengths. Your next adventure begins with who you are today.'],start:['開啟我的旅程','Begin my journey'],resume:['繼續我的旅程','Continue my journey'],revisit:['重溫我的旅程','Revisit my journey'],caption:['下一站，未知的自己','Next stop: the person you could become'],
 results:['冒險成果','Adventure achievements'],learned:['已學單字','Words learned'],bagPower:['放進行囊的力量','Strength for the road'],footprints:['旅程足跡','Chapters explored'],oneStep:['每一關，向前一步','A step forward with every chapter'],growth:['累積成長','Experience gained'],due:['今日到期','Due now'],familiar:['熟悉的字，再見一次','Meet familiar words again'],milestones:['三個累積單字里程碑','Three cumulative vocabulary milestones'],
 mapTitle:['你的冒險，正在展開','Your adventure is unfolding'],mapSubtitle:['一百關，累積 7,000 字','100 chapters. 7,000 words.'],mapTag:['100 關 · 7,000 字','100 chapters · 7,000 words'],previousMap:['上一區地圖','Previous map region'],nextMap:['下一區地圖','Next map region'],chooseRegion:['選擇旅程區域','Choose a journey region'],current:['當前冒險','Current adventure'],completed:['已通關','Completed'],unexplored:['待探索','Unexplored'],
 ritual:['每次出發，都比上次更有力量','Set out a little stronger each time'],reviewOld:['重溫舊知','Revisit what you know'],reviewOldHint:['每輪最多重溫 20 個到期與上一段單字','Review up to 20 due and recent words per round'],exploreNew:['探索新字','Discover new words'],exploreNewHint:['在故事裡認識新夥伴','Meet new companions in the story'],takeTrial:['迎接試煉','Meet the challenge'],takeTrialHint:['答錯再練，理解後前進','Try again and move forward'],
 wordsIntro:['每一個記住的單字，都是下一段旅程的底氣。','Every word you remember gives you confidence for the road ahead.'],searchPlaceholder:['搜尋英文或中文意思','Search a word or English definition'],search:['搜尋單字','Search words'],filter:['篩選單字','Filter words'],allWords:['全部已學單字','All learned words'],growing:['持續練習','Still practising'],mastered:['漸漸熟練','Growing familiar'],reviewWords:['重溫我的單字','Review my words'],journalIntro:['你走過的每一步，都在這裡留下痕跡。','Every step you take leaves a trace here.'],export:['匯出旅程備份','Export a journey backup'],import:['匯入備份','Import a backup'],backupHint:['訪客進度儲存在此瀏覽器；登入後可同步，也可匯出自己的備份。','Guest progress stays in this browser. Sign in to sync, or export your own backup.'],footerBrand:['WORD ODYSSEY · 字旅','WORD ODYSSEY'],footer:['不必一次走得很遠，只要願意，再往前一點。','You need not travel far at once. Just take one more step.'],targets:['1,200 → 2,000 → 7,000 字','1,200 → 2,000 → 7,000 words'],onRoad:['Word Odyssey · 旅途中','Word Odyssey · On the road'],leave:['離開本次練習','Leave this practice'],importTitle:['將備份旅程帶回來？','Bring back your saved journey?'],importWarning:['這會取代目前瀏覽器中的進度。建議先匯出現在的旅程。','This replaces progress in this browser. Export your current journey first if you want to keep it.'],cancel:['取消','Cancel'],replace:['取代並匯入','Replace and import'],
 language:['切換為全英文','Switch to Traditional Chinese'],languageLocked:['請先完成或離開本次練習，再切換語言。','Finish or leave this practice before changing language.'],
 synced:['另一個分頁已更新旅程，已同步最新進度；請重新開啟本次任務。','Another tab updated your journey. The latest progress is loaded; please reopen your quest.'],saveFailed:['目前無法儲存進度，請到成長手札匯出備份。','Progress could not be saved. Please export a backup from your journal.'],
 rank1:['初行旅人','First-time traveller'],rank2:['勇敢探索者','Brave explorer'],rank3:['遠行英雄','Travelling hero'],rank4:['歸來的英雄','Returning hero'],keepGoing:['持續向前','Keep moving forward'],allDone:['百關完成 · 7,000 字已學 · 持續複習，讓記憶更穩固','100 chapters complete · 7,000 words learned · Keep reviewing to strengthen your memory'],questFootnote:['第 {id} 關 · 每次最多 10 個新字 · 隨時歸來，接續旅程','Chapter {id} · Up to 10 new words per quest · Return whenever you wish'],chapterRange:['第 {from}–{to} 關','Chapters {from}–{to}'],cumulative:['累積單字','total words'],stageLabel:['第 {id} 關 {title}，{status}','Chapter {id}: {title}, {status}'],available:['可挑戰','Ready to explore'],locked:['尚未解鎖','Locked'],wordCount:['{n} 個單字','{n} words'],chapterTotal:['通關累積 {n} 字','{n} words by chapter completion'],waitChapter:['等待前一關通關','Complete the previous chapter'],dataPending:['本關詞表整理中','Vocabulary being prepared'],reviewLearned:['複習本章已學單字','Review learned words in this chapter'],acceptQuest:['接受召喚 · {n} 字任務','Accept the call · {n}-word quest'],lockedHint:['前往目前關卡，一步一步解鎖','Visit your current chapter to unlock the next step'],completeHint:['持續複習，讓每個字更熟悉','Keep reviewing to make every word more familiar'],questHint:['先複習，再探索；完成小任務即保存','Review, then explore. Every completed quest is saved.'],
 noSpeech:['這個瀏覽器沒有語音功能，仍可閱讀與練習。','Speech is not available in this browser. You can still read and practise.'],speechFailed:['語音暫時無法播放，請稍後再試。','Audio is unavailable right now. Please try again later.'],startError:['請從目前已解鎖的關卡開始。','Please begin with your current unlocked chapter.'],dataError:['本關資料尚未備妥，請稍後再試。','This chapter is not ready. Please try again later.'],noReview:['先完成第一個單字任務，就能回來複習。','Complete your first word quest to unlock review.'],
 callLocation:['第 {id} 關 / {place}','Chapter {id} / {place}'],mentor:['導師指引','The mentor’s guidance'],mentorHint:['先重溫到期與上一段學過的單字。','First revisit words due for review and from your last quest.'],threshold:['跨越門檻','Cross the threshold'],newPlan:['這次認識 {n} 個新字。','Meet {n} new words in this quest.'],trial:['面對試煉','Face the trial'],trialHint:['本輪辨認字義，後續複習練拼字；答錯會再遇見。','Recognise meanings now; practise spelling in later reviews. Missed words return.'],reward:['帶著收穫歸來','Return with your reward'],rewardHint:['完成這段任務，保存單字與成長。','Complete the quest to save your new words and experience.'],ready:['我準備好了','I’m ready'],phaseCall:['接受召喚','The call'],phaseReward:['帶回力量','The return'],missingWord:['找不到這個單字，請重新開啟任務。','This word could not be found. Please reopen the quest.'],imagine:['讀一遍、想像一個使用情境，再把這個字放進你的行囊。','Read it aloud, imagine when you might use it, then carry it with you.'],newWord:['新字','New word'],newPower:['一個新字，一份新的力量','A new word, a new strength'],studyHint:['先認識字義，再試著遮住中文，說出它的意思。','Read the English definition. Then cover it and explain the word in your own words.'],pronounce:['播放 {word} 發音','Pronounce {word}'],practiceSoon:['本輪先辨認字義；後續複習再練回想拼字，可使用提示。','Recognise meanings first; later reviews offer spelling practice with hints.'],readyTrial:['準備接受試煉','Ready for the trial'],carryWord:['帶上這個單字','Carry this word with me'],oldWords:['舊字複習','Word review'],wordTrial:['單字試煉','Word challenge'],recall:['試著寫出這個英文單字','Can you write the English word?'],recognise:['你還記得這個字的意思嗎？','What does this word mean?'],reviewHint:['先把舊知帶回來，再走向新風景。','Bring back familiar knowledge before exploring somewhere new.'],challengeHint:['慢慢想，答錯的單字會再陪你練一次。','Take your time. Any word you miss will return for another try.'],spellLabel:['輸入英文（不區分大小寫）','Type the English word (any letter case)'],checkAnswer:['確認答案','Check answer'],correct:['記住了，這份力量屬於你。','You remembered. This strength is yours.'],incorrect:['沒關係，再遇見一次，就多熟悉一點。','That’s all right. Another encounter makes it more familiar.'],retry:['稍後會再出現，答對後再前進。','It will return shortly. Answer correctly to move on.'],listen:['聽發音','Listen'],next:['繼續前進','Keep going'],nextHint:['帶著提示繼續','Continue with the hint'],
 reviewDone:['這輪複習完成','This review round is complete'],stageDone:['這一關，你做到了！','You completed this chapter!'],questDone:['小任務完成，力量已放進行囊','Quest complete. New strengths are yours.'],reviewReturn:['每一次重溫，都讓下一次出發更有把握。','Every review gives you more confidence for the next adventure.'],questReturn:['你把這段新學的詞語寫進旅人手札。歇一會兒，再帶著力量繼續這一關的冒險。','You record your new words in your traveller’s journal. Rest a moment, then return to this chapter with fresh strength.'],progressLine:['第 {id} 關：{n} / {quota} 字 · 全程 {total} / 7,000 字','Chapter {id}: {n} / {quota} words · Journey: {total} / 7,000 words'],returnMap:['回到冒險地圖','Return to the map'],nextChapter:['探索下一關','Explore the next chapter'],continueChapter:['繼續這一關','Continue this chapter'],saved:['進度已保存在此瀏覽器','Progress saved in this browser'],notSaved:['進度尚未儲存，請至成長手札匯出備份','Progress not saved. Please export a backup from your journal.'],wordSummary:['行囊裡已有 {n} / {target} 字 · 顯示 {shown} 字','Your collection: {n} / {target} words · Showing {shown} words'],first100:['先呈現前 100 字，輸入關鍵字可縮小範圍','First 100 shown; search to narrow the results'],dueNow:['該重溫了','Time to revisit'],mastery:['熟練進度 {n} / 3','Familiarity {n} / 3'],notFound:['還沒找到這個單字','No matching words yet'],emptyBag:['你的行囊，正等著第一份收穫','Your collection awaits its first discovery'],searchAgain:['試試別的關鍵字，或切換篩選條件。','Try another search or change the filter.'],firstQuest:['完成第一個任務，學過的單字就會出現在這裡。','Finish your first quest and your learned words will appear here.'],spacedWords:['經過間隔複習的熟練字','Words strengthened through spaced review'],completedChapters:['已完成關卡','Completed chapters'],travelling:['旅途中','In progress'],firstPage:['故事的第一頁，留給出發的你','The first page is waiting for you'],firstPageHint:['不需要準備好所有勇氣。完成一段小任務，就會留下第一筆成長紀錄。','You do not need all your courage at once. Finish a small quest to write your first entry.'],exported:['旅程備份已匯出，記得妥善保存。','Your journey backup has been exported. Keep it somewhere safe.'],left:['已完成紀錄與未完成練習草稿都會保留；下次可接續。','Completed words and unfinished practice are saved. Resume your draft next time.'],invalidBackup:['這份檔案不是有效的字旅備份，原有進度已保留。','This is not a valid Word Odyssey backup. Your current progress is unchanged.'],imported:['旅程已匯入，歡迎繼續出發。','Journey imported. Welcome back to the road.'],storageUnavailable:['瀏覽器無法儲存進度，可使用手札的匯出備份。','This browser cannot save progress. Use the journal to export a backup.'],
 definitionMissing:['英文解釋整理中；本題為抄寫練習，不計入主動回憶熟練。','English definition is being prepared. This is copying practice and does not count towards recall mastery.'],listenSpell:['看字、聽發音，再練習輸入','Look, listen and spell the word'],cloudApplied:['雲端旅程已載入。','Your cloud journey has been loaded.'],
 newWordsSave:['完成這批才計入已學新字；中途離開可接續草稿。','New words count after this batch. Unfinished practice can be resumed.'],
 mentorPlan:['今日到期 {due} 字；這輪先複習 {n} 字（最多 20 字），其餘可接續練習。','{due} words due now; review {n} in this round (up to 20). Remaining words stay due for another round.'],
 reviewRound:['今日到期 {due} 字 · 這輪待複習 {n} / {total} 字','Due now: {due} · Remaining in this round: {n} / {total}'],
 reviewRemaining:['今日仍有 {n} 字到期；可依自己的步調接續下一輪。','{n} words are still due. Continue with another round at your own pace.'],
 continueReview:['接續下一輪複習','Review the next round'],
 copyPractice:['看字抄寫練習','Copy the word'],
 recallNeeded:['已累積到期複習；還需要一次到期後首次拼字答對，才算熟練。','Spaced reviews recorded. One successful first-attempt spelling review when due is still needed for mastery.'],
 reviewHistory:['複習活動紀錄','Review activity'],
 reviewHistoryHint:['保留最近 100 輪，包含中途離開的練習。複習不會重複獲得 XP。','The most recent 100 rounds are kept, including unfinished practice. Reviews do not award extra XP.'],
 noReviewHistory:['完成新字任務後，複習活動會記錄在這裡。','After your first word quest, review activity will appear here.'],
 reviewSummary:['本輪 {count} 字 · 首次作答 {attempts} 字 · 首次答對 {correct} 字 · 重試 {retries} 次','Round: {count} words · First attempts: {attempts} · First correct: {correct} · Retries: {retries}'],
 reviewFinished:['本輪完成','Round completed'],reviewInterrupted:['本輪未完成','Round unfinished'],
};
const LOCALE_KEY = 'word-odyssey-locale';
export let locale = 'zh';
try { if(typeof window!=='undefined')locale = window.localStorage.getItem(LOCALE_KEY) === 'en' ? 'en' : 'zh'; } catch {}
export function t(key, params = {}) {
 const entry = messages[key];
 if (!entry) throw new Error(`Unknown translation key: ${key}`);
 return entry[locale === 'en' ? 1 : 0].replace(/\{(\w+)\}/g, (_,name) => String(params[name] ?? `{${name}}`));
}
export function setLocale(next) { locale = next === 'en' ? 'en' : 'zh'; try { if(typeof window!=='undefined')window.localStorage.setItem(LOCALE_KEY,locale); } catch {} }
export function applyTranslations() {
 document.documentElement.lang = locale === 'en' ? 'en' : 'zh-Hant-TW';
 document.title=t('title'); document.querySelector('meta[name="description"]').content=t('description');
 document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));
 document.querySelectorAll('[data-i18n-text]').forEach(el=>{const node=[...el.childNodes].find(n=>n.nodeType===3&&n.textContent.trim());if(node)node.textContent=t(el.dataset.i18nText);});
 document.querySelectorAll('[data-i18n-aria]').forEach(el=>el.setAttribute('aria-label',t(el.dataset.i18nAria)));
 document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));
}
export function wordMeaning(word) { return locale === 'en' ? hasEnglishDefinition(word) ? word.definition : t('definitionMissing') : word.meaning; }
export function hasEnglishDefinition(word) { return typeof word.definition === 'string' && word.definition.trim() && !/[\u3400-\u9fff]/u.test(word.definition); }
export function stageTitle(stage) { const title=getReading(stage.id).title; return locale === 'en' ? title.en : title.zh; }
export function stagePlace(stage) { return locale === 'en' ? stage.region : stage.place; }
const englishCalls = [
 ['The village post carrier has lost an important letter. Help uncover the clues.','You deliver the recovered letter and bring the first story to a happy ending.'],
 ['A lost traveller needs your help. Gather the clues and find the right direction.','You reach the crossroads together. Your compass points towards the next adventure.'],
 ['The bookshop mentor leaves an unfinished page of notes. Discover the secret between the lines.','You add your discoveries to the notes. The mentor rewards your courage with a bookmark.'],
 ['An unfamiliar landscape lies beyond the stone bridge. Prepare yourself and take that first step.','You cross the bridge and find that unknown places can become familiar too.'],
 ['New friends at the market invite you to work together. Listening and speaking are both your strengths.','Together you finish the task. With friends beside you, the road feels less lonely.'],
 ['Mist has hidden the signposts. Connect familiar clues to find the path again.','The mist clears. You learn to trust what you have gathered, even when the way is uncertain.'],
 ['Clouds gather in the distance. Organise your pack for the challenge ahead.','The rain stops. With your pack ready, you set off towards the next stop.'],
 ['The tower door slowly opens. Bring everything you have learned to the guardian’s trial.','The tower bells ring for you. You passed the trial and discovered your own strength.'],
 ['An unlit lantern waits for you to bring back a spark.','The lantern shines again, lighting the road for you and the next traveller.'],
 ['You have reached the end of this part of the journey. Look back, then face one final challenge.','You return with new words and courage. The familiar world feels wider because you have grown.'],
];
export function stageStory(stage, type='description') {
 if(locale!=='en') return stage[type];
 const call=englishCalls[(stage.id-1)%10];
 if(type==='returnStory')return `${stage.region} traveller’s journal: ${call[1]}`;
 if(type==='invitation')return `You arrive in ${stage.region}. ${call[0]} Collect ${stage.quota} words in this chapter, one small quest at a time.`;
 return `${stage.region}: ${call[0]}`;
}

const englishParts = {'名詞':'noun','動詞':'verb','形容詞':'adjective','冠詞':'article','介系詞':'preposition','連接詞':'conjunction','助動詞':'auxiliary verb','代名詞':'pronoun','副詞':'adverb','數詞':'numeral','感嘆詞':'interjection','限定詞':'determiner','專有名詞':'proper noun','片語':'phrase','所有格':'possessive','關係副詞':'relative adverb','副詞片語':'adverbial phrase','動詞片語':'verb phrase','序數詞':'ordinal numeral'};
export function wordPos(word, language=locale){const pos=String(word?.pos||'');return language==='en'?pos.split('／').map(part=>englishParts[part]||'').filter(Boolean).join(' / '):pos;}
